name: CI/CD Deploy to Tomcat
on:
  push:
    branches:
      - master

jobs:
  # BUILD JOB
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build WAR
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: target/*.war

  # DEPLOY DEV
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Deploy to DEV
        run: |
            curl -v -u ${{ secrets.DEV_USER }}:${{ secrets.DEV_PASSWORD }} \
            --upload-file *.war \
            "http://${{ secrets.DEV_HOST }}:8080/manager/text/deploy?path=/myapp&update=true"

  # DEPLOY TEST
  deploy-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Deploy to TEST
        run: |
          curl -v -u ${{ secrets.TEST_USER }}:${{ secrets.TEST_PASSWORD }} \
          --upload-file *.war \
          "http://${{ secrets.TEST_HOST }}:8080/manager/text/deploy?path=/myapp&update=true"

  # DEPLOY PRO
  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Deploy to PROD
        run: |
          curl -v -u ${{ secrets.PROD_USER }}:${{ secrets.PROD_PASSWORD }} \
          --upload-file *.war \
          "http://${{ secrets.PROD_HOST }}:8080/manager/text/deploy?path=/myapp&update=true"
